controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    wheels_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheels_velocity_controller:
  ros__parameters:
    joints:
      - wheel_right_joint
      - wheel_left_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity